//
// Created by tianGe on 2017/8/11.
//

#ifndef NDKDEMO_COM_XYP_TIANGE_NDKDEMO_NATIVEHELPER_H
#define NDKDEMO_COM_XYP_TIANGE_NDKDEMO_NATIVEHELPER_H

#endif //NDKDEMO_COM_XYP_TIANGE_NDKDEMO_NATIVEHELPER_H
